# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16object_detection.proto\x12\x10object_detection\"\r\n\x0bInitRequest\"!\n\x0cInitResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"!\n\x0c\x43loseRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"\"\n\rCloseResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"\\\n\rDetectRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0b\n\x03\x66ps\x18\x02 \x01(\x05\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x05\x12\x12\n\nframe_data\x18\x04 \x01(\x0c\"\x16\n\x06\x42\x42oxes\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"{\n\x0e\x44\x65tectResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x12\x13\n\x0breq_dropped\x18\x03 \x01(\x08\x12(\n\x06\x62\x62oxes\x18\x04 \x01(\x0b\x32\x18.object_detection.BBoxes2\x80\x02\n\x08\x44\x65tector\x12N\n\x0binit_client\x12\x1d.object_detection.InitRequest\x1a\x1e.object_detection.InitResponse\"\x00\x12U\n\x10\x63lose_connection\x12\x1e.object_detection.CloseRequest\x1a\x1f.object_detection.CloseResponse\"\x00\x12M\n\x06\x64\x65tect\x12\x1f.object_detection.DetectRequest\x1a .object_detection.DetectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITREQUEST']._serialized_start=44
  _globals['_INITREQUEST']._serialized_end=57
  _globals['_INITRESPONSE']._serialized_start=59
  _globals['_INITRESPONSE']._serialized_end=92
  _globals['_CLOSEREQUEST']._serialized_start=94
  _globals['_CLOSEREQUEST']._serialized_end=127
  _globals['_CLOSERESPONSE']._serialized_start=129
  _globals['_CLOSERESPONSE']._serialized_end=163
  _globals['_DETECTREQUEST']._serialized_start=165
  _globals['_DETECTREQUEST']._serialized_end=257
  _globals['_BBOXES']._serialized_start=259
  _globals['_BBOXES']._serialized_end=281
  _globals['_DETECTRESPONSE']._serialized_start=283
  _globals['_DETECTRESPONSE']._serialized_end=406
  _globals['_DETECTOR']._serialized_start=409
  _globals['_DETECTOR']._serialized_end=665
# @@protoc_insertion_point(module_scope)
